### ISSUE TITLE
Public link password check on API level

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-reva#312]
As discovered by @individual-it this is not implemented yet.

Password / authentication should be enforced for any API call to the public-files endpoint.

@refs FYI

@individual-it did we have any related disabled tests or new tests ?

**Comment by individual-it** [comment]
there are tests that check that https://github.com/owncloud/core/blob/9d143b41bda3d5c2bb265a220d0c5dfe8eb584f9/tests/acceptance/features/apiSharePublicLink1/changingPublicLinkShare.feature#L231

I only had the problem when trying to configure cs3org/reva and didn't know how to configure the auth provider correctly. Now it works also with cs3org/reva

**Comment by refs** [comment]
@PVince81 reopening this issue

**Comment by refs** [comment]
while working on this found a bug on Phoenix. Reported [here](https://github.com/owncloud/phoenix/issues/3722)

**Comment by refs** [comment]
as it turns out tests are green. The only remaining red are related to permissions. Good gymnastics for running tests nevertheless.

**Comment by refs** [comment]
@PVince81 as it turns out, the handler inlines request authentication: https://github.com/cs3org/reva/blob/master/internal/http/services/owncloud/ocdav/dav.go#L117-L121 which ripples down to `pkg/auth/manager/publicshares/publicshares.go` and down to the implementation: https://github.com/refs/reva/blob/f599518bd52aa65dd467b7d921151481efbcfa0e/pkg/publicshare/manager/json/json.go#L394, which bubbles up all the way to the handler.
